<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>distsharp</ToolCommandName>
    <PackageId>DistSharp</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DistSharp.Core\DistSharp.Core.csproj" />
    <ProjectReference Include="..\DistSharp.Roslyn\DistSharp.Roslyn.csproj" />
    <ProjectReference Include="..\DistSharp.Providers\DistSharp.Providers.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
